### PR TITLE
Fix: #25 make emergency contact info nullable

### LINKED ISSUE #25: Emergency contact info should be nullable
When trying to use the fill-shifts command I'm getting this error: 

image

It seems that the Emergency contact information is mandatory but I have it blank on my profile

image

I will create a PR fixing this 🫡 

Just creating the issue for tracking the problem

### PR DESCRIPTION
**Pull request by Linkmetal**
This PR fixes #25

### CODE REVIEW

File: src/infrastructure/factorial-client/schema/MySelf.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
-import { z } from "zod";
 import { Employee } from "./Employee.js";
+import { z } from "zod";
```
Comment (DanielRamosAcosta) [inline src/infrastructure/factorial-client/schema/MySelf.ts:2]:
```suggestion
import { z } from "zod";
import { Employee } from "./Employee.js";
```
